package ThinkingInJava.Arrays.P565;

import java.util.*;
import static java.lang.Math.*;
//Exercise 3:   (4) Write a method that creates and initializes
// a twodimensional array of double. The size of the array is
// determined by the arguments of the method, and the initialization
// values are a range determined by beginning and ending values that
// are also arguments of the method. Create a second method that will
// print the array generated by the first method. In main( ) test the
// methods by creating and printing several different sizes of arrays.

public class TwoDimArray {
    static Random random = new Random(47);
    public static double[][][] make3Darray(int xsize, int ysize, int zsize, double start, double end){
        double[][][] dimArray = new double[xsize][ysize][zsize];
        for(int i = 0; i < xsize; i++)
            for(int j = 0; j < ysize; j++)
                for(int h = 0; h < zsize; h++)
                    dimArray[i][j][h] = round((start + random.nextDouble()*(end - start))*100)/100d;
        return dimArray;
    }
    public static double[][] make2DArray(int xsize, int ysize, double start, double end){
        double[][] dimArray = new double[xsize][ysize];
        for (int i = 0; i < xsize; i++)
            for (int j = 0; j < ysize; j++)
            dimArray[i][j] = round((start + random.nextDouble()*(end - start))*100)/100d;
            return dimArray;
    }
    public static void printArray(double[][] array){
        System.out.println(Arrays.deepToString(array));
    }
    public static void printArray(double[][][] array){
        System.out.println(Arrays.deepToString(array));
    }


    public static void main(String[] args) {
        printArray(make2DArray(5,5,3,9));
        printArray(make3Darray(5,3,2,3,8));
        System.out.println(Arrays.deepToString(new Integer[3][3][3]));
    }
}
